name: Update SOTA Map

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - 'master'

permissions:
  contents: write

env:
  CALLSIGN: ${{ vars.CALLSIGN }}
  GEOCACHING_HU_UID: ${{ vars.GEOCACHING_HU_UID }}
  GEOCACHING_HU_NEMESIS_UID: ${{ vars.GEOCACHING_HU_NEMESIS_UID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Cache openstreetmap tiles
        uses: actions/cache@v4
        with:
          key: osm-tile-cache
          path: tile_cache/

      - name: Install png postprocess tooling
        run: |
          sudo apt-get install -y --no-install-recommends pngcrush pngquant

      - name: Generate sota report
        run: |
          uv run main.py
          mkdir -p output
          mv sota.html output/
          ./postprocess-png.sh sota.png output/sota.png

      - name: Generate geocaching report
        run: |
          uv run geocaching_hu_api_viz.py
          mkdir -p output
          mv geocaching_stats.svg output/geocaching.svg

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: gh-pages
